from __future__ import annotations

from typing import Protocol
from uuid import UUID

from job_discovery.dashboard.models import (
    DashboardJobUserStatus,
    DashboardUserStateSnapshot,
    DiscoveryRunReport,
)
from job_discovery.domain.models import CoarseScore, JobRecord, JobSourceListing
from job_discovery.domain.settings import DiscoverySettings, DiscoverySettingsInput, ScoringProfileInput, UserScoringProfile


class DashboardJobReader(Protocol):
    def list_records(self) -> list[JobRecord]: ...

    def list_all_listings(self) -> list[JobSourceListing]: ...

    def get_record(self, job_id: UUID) -> JobRecord | None: ...

    def list_listings(self, job_id: UUID) -> list[JobSourceListing]: ...


class DashboardUserStateRepository(Protocol):
    def get_snapshot(self, user_id: str) -> DashboardUserStateSnapshot: ...

    def mark_job_viewed(self, user_id: str, job_id: UUID) -> None: ...

    def set_job_status(self, user_id: str, job_id: UUID, status: DashboardJobUserStatus) -> None: ...

    def mark_run_viewed(self, user_id: str, run_id: str) -> None: ...

    def list_blocked_companies(self, user_id: str) -> list[str]: ...

    def block_company(self, user_id: str, company: str) -> list[str]: ...

    def unblock_company(self, user_id: str, company: str) -> list[str]: ...

    def get_scoring_profile(self, user_id: str) -> UserScoringProfile | None: ...

    def save_scoring_profile(self, user_id: str, profile: ScoringProfileInput) -> UserScoringProfile: ...

    def list_scoring_profiles(self) -> list[UserScoringProfile]: ...

    def get_discovery_settings(self) -> DiscoverySettings: ...

    def save_discovery_settings(self, settings: DiscoverySettingsInput) -> DiscoverySettings: ...

    def record_user_score(
        self, user_id: str, job_id: UUID, score: CoarseScore, score_version: str, profile_version: int
    ) -> None: ...

    def mark_user_score_queued(self, user_id: str, job_id: UUID, profile_version: int) -> None: ...

    def record_user_score_failure(
        self, user_id: str, job_id: UUID, score_version: str, profile_version: int, error: str
    ) -> None: ...

    def record_discovery_run(self, report: DiscoveryRunReport) -> None: ...

    def list_discovery_runs(self) -> list[DiscoveryRunReport]: ...
